version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,glue,iam,sts
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./docker/trino/catalog:/etc/trino/catalog
    depends_on:
      - minio
      - localstack

  mock_generator:
    build:
      context: .
      dockerfile: docker/mock_generator/Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
      - minio
      - trino

  init:
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt &&
               python scripts/setup_environment.py"
    depends_on:
      - localstack
      - minio
      - trino

volumes:
  minio_data: 